// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_HrCiC6fqyyggOULFxXNtGaFKa4pCcA',
    appId: '1:974477755822:android:436ab41b7b561be12ff43f',
    messagingSenderId: '974477755822',
    projectId: 'socailx-2e7b4',
    databaseURL: 'https://socailx-2e7b4-default-rtdb.firebaseio.com',
    storageBucket: 'socailx-2e7b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_etig-TU9Ub7TUE8eRrTHP-7okBKAb_0',
    appId: '1:974477755822:ios:555903eda58234482ff43f',
    messagingSenderId: '974477755822',
    projectId: 'socailx-2e7b4',
    databaseURL: 'https://socailx-2e7b4-default-rtdb.firebaseio.com',
    storageBucket: 'socailx-2e7b4.appspot.com',
    iosBundleId: 'com.tele.x.telex',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCor8Tm3jp8Gm1qPg24PZXiSDDQHOSxj-Y',
    appId: '1:974477755822:web:92cb365375c342ac2ff43f',
    messagingSenderId: '974477755822',
    projectId: 'socailx-2e7b4',
    authDomain: 'socailx-2e7b4.firebaseapp.com',
    databaseURL: 'https://socailx-2e7b4-default-rtdb.firebaseio.com',
    storageBucket: 'socailx-2e7b4.appspot.com',
    measurementId: 'G-L11WEQSN3F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_etig-TU9Ub7TUE8eRrTHP-7okBKAb_0',
    appId: '1:974477755822:ios:555903eda58234482ff43f',
    messagingSenderId: '974477755822',
    projectId: 'socailx-2e7b4',
    databaseURL: 'https://socailx-2e7b4-default-rtdb.firebaseio.com',
    storageBucket: 'socailx-2e7b4.appspot.com',
    iosBundleId: 'com.tele.x.telex',
  );

}